[google]
client_id = "634249773968-9l0g01pcnbkto2l8lam0e8vnfjg7fg99.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://wordpress-image-checker-sw-pd.streamlit.app"

